// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2mR0GOZtU7udwPx_fcZFRvBI286WBfFA',
    appId: '1:274917202323:web:d13368220a49ef10e37066',
    messagingSenderId: '274917202323',
    projectId: 'chatting-app-22110',
    authDomain: 'chatting-app-22110.firebaseapp.com',
    storageBucket: 'chatting-app-22110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_FW79glqcXm8kz1LbBTT-70iHZ8D6bI',
    appId: '1:274917202323:android:6617a30e3ed2b6f4e37066',
    messagingSenderId: '274917202323',
    projectId: 'chatting-app-22110',
    storageBucket: 'chatting-app-22110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48V2GcDCSAZG9FLVD52rKxO5UVF4UcQY',
    appId: '1:274917202323:ios:45514bb4e42c0134e37066',
    messagingSenderId: '274917202323',
    projectId: 'chatting-app-22110',
    storageBucket: 'chatting-app-22110.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA48V2GcDCSAZG9FLVD52rKxO5UVF4UcQY',
    appId: '1:274917202323:ios:45514bb4e42c0134e37066',
    messagingSenderId: '274917202323',
    projectId: 'chatting-app-22110',
    storageBucket: 'chatting-app-22110.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2mR0GOZtU7udwPx_fcZFRvBI286WBfFA',
    appId: '1:274917202323:web:046f343f1f29fb1ae37066',
    messagingSenderId: '274917202323',
    projectId: 'chatting-app-22110',
    authDomain: 'chatting-app-22110.firebaseapp.com',
    storageBucket: 'chatting-app-22110.appspot.com',
  );
}
